### PR TITLE
- fixes regression in logic flow through operation deserialization

### PR DESCRIPTION
**Pull request by thecodefactory**
Cleaner attempt at previous PR #334 

Fixes libbitcoin/libbitcoin-server#134

### CODE REVIEW

**Comment by skaht** [comment]
Congrats in advance for hunting this bug down:-) Will compile this weekend.

**Comment by thecodefactory** [comment]
Great, would like to hear your feedback!

**Comment by evoskuil** [comment]
Thanks!

**Comment by thecodefactory** [comment]
Re-issued as #337

**Pull request closed without merging**
