### PR TITLE
Update src/wallet/dictionary.cpp

### PR DESCRIPTION
**Pull request by ebCrypto**
with regards to #1060 
I copied the source file https://raw.githubusercontent.com/bitcoin/bips/master/bip-0039/spanish.txt adding the necessary "

### CODE REVIEW

**Comment by thecodefactory** [comment]
Re-ordering the english can't be correct.  I'm not sure the dictionaries need adjustment either.  Any further info provided there?

**Comment by thecodefactory** [comment]
> I grabbed the Spanish words with special characters from the bip-0039 source file

The original word lists were taken from:

https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md.

Can you clarify what the difference is?

**Comment by thecodefactory** [comment]
@ebCrypto I'm going to close this in favor of #1073 

Let me know if you think it doesn't address the issue and we can revisit.

**Comment by ebCrypto** [comment]
Ok it makes sense!

**Pull request closed without merging**
