### PR TITLE
This community NEEDS to adopt a code of conduct. Recent events make t…

### PR DESCRIPTION
**Pull request by jrmithdobbs**
…his glaringly obvious.

### CODE REVIEW

**Comment by evoskuil** [comment]
Sorry, this is not a safe space.

**Comment by jrmithdobbs** [comment]
@genjix Coments on this please. You know me.

**Comment by jrmithdobbs** [comment]
Knowing that this project is led by an incorporated entity means you are saying that said entity does in fact plan on discriminating against people based on race/color/religion/creed?

**Comment by jrmithdobbs** [comment]
You too @phantomcircuit.

**Comment by hoffmabc** [comment]
lol wut?

**Comment by jrmithdobbs** [comment]
If it is no longer backed by the possibly defunct Bitcoin Consultancy that comment may be inaccurate. It was; however, at one time.

**Comment by evoskuil** [comment]
I plan on discriminating on whatever basis I feel like. You are fee to do the same.

**Comment by jrmithdobbs** [comment]
So where exactly is your Bitware Co. incorporated? You're admitting to intent to violate US federal law on a public forum.

**Comment by evoskuil** [comment]
Washington State.

**Comment by hoffmabc** [comment]
I'm sorry I'm confused wtf @jrmithdobbs is talking about. Does this have anything to do with libbitcoin?

**Comment by phantomcircuit** [comment]
libbitcoin has been a community project since it's inception, bitcoin
consultancy supported but did not run the project

regardless bitcoin consultancy ltd is dissolved

**Comment by jrmithdobbs** [comment]
So then you admit that Bitware has exclusionary practices based on gender/race/creed/religion?

**Comment by evoskuil** [comment]
@jrmithdobbs  Fuck Off

**Comment by hoffmabc** [comment]
Clearly troll so reported.

image

**Comment by evoskuil** [comment]
Maybe we should merge the PR and then ban him using his own nanny rules.

**Comment by jrmithdobbs** [comment]
It's a fantastic way to keep recruiters from calling constantly. Thanks for the personal attacks and demonstrating why I'm proposing this.

**Comment by jrmithdobbs** [comment]
This policy is and has been adopted by, for instance, ZeroMQ, amongst many other highly visible and respected projects. Your knee-jerk response is a tell-tale sign of the need for these policies. It may be too late for bitcoin but after watching what happened to greg and others recently I will no longer be silent about it.

**Comment by jrmithdobbs** [comment]
But please keep digging, I've said much worse things on the internet than that I dislike job recruiters/middlemen.

Maybe you should start with full-disclosure where I warned of Mt Gox doing exactly what it seems to have been caught doing and performed an external post-mortem on their first major compromise?

I walked away from this community, in part, for the reasons these CoCs are supposed to prevent.

I'm not perfect, I've been an asshole, it doesn't mean I'm not trying to improve that.

**Comment by evoskuil** [comment]
I am a ZeroMQ maintainer. [C41](http://rfc.zeromq.org/spec:22) states:

> Administrators SHOULD block or ban "bad actors" who cause stress and pain to others in the project. This should be done after public discussion, with a chance for all parties to speak. A bad actor is someone who repeatedly ignores the rules and culture of the project, who is needlessly argumentative or hostile, or who is offensive, and who is unable to self-correct their behavior when asked to do so by others.

I have not banned you yet, but according to the rules of an organization that I contribute to, and that you consider a model, I'd be within my rights to do so.

But libbitcoin rules are quite clear, we don't have any. If you contribute you tend to earn respect. If you drop in from nowhere and start telling people how they need to act, you are likely to be politely dismissed. If you start threatening people with state aggression, you will probably be told to Fuck Off (or maybe to Bugger Off or Piss Off, depending on the maintainer). I don't care if you are an asshole or what you have done. But if you want anyone to care then stop being a douchetard and contribute something of value.

**Comment by hoffmabc** [comment]
:+1:

**Comment by jrmithdobbs** [comment]
You know I had cc'ed the author of that clause on twitter before saying anything about zeromq here, yes?

You explicitly state you will discriminate against anyone you want and I'm the bad actor?

Classy.

**Comment by evoskuil** [comment]
@hintjens You have been trolled.

**Comment by jrmithdobbs** [comment]
Just ... no. Ugh. I don't know why i bothered, bitcoin is too far gone to fix this issue.

I apologize for wasting my time.

**Comment by jrmithdobbs** [comment]
Hopefully the core devs will be more amenable to sanity.

**Comment by hoffmabc** [comment]
hah @jrmithdobbs peace out.

**Comment by unclediazepam** [comment]
BTFO
T
F
O

SJW crybullies pls go.

**Pull request closed without merging**
