### PR TITLE
update readme with link to williams presentation of libbitcoin

### PR DESCRIPTION
**Pull request by dan-mi-sun**
Don't know if it'll be considered bad smell to have link to presentation in readme - but the talk is a fantastic introduction to the project.

### CODE REVIEW

**Comment by dan-mi-sun** [comment]
If more appropriate I can update here if that is preferable:

https://github.com/libbitcoin/libbitcoin.github.io/blob/master/index.html

**Comment by evoskuil** [comment]
Thanks @dan-mi-sun. I'd like to see this highlighted, but would prefer the website and/or the wiki. The presentation spans all of the libbitcoin repos, not just the common lib, so the website is probably better than the wikis.

**Comment by dan-mi-sun** [comment]
OK - will submit another PR

**Comment by dan-mi-sun** [comment]
@evoskull - do you know what the deployment flow is with the website? If I create a PR associated to: https://github.com/libbitcoin/libbitcoin.github.io/blob/master/index.html

If merged, will this then automatically be deployed? Or should I speak with @jaromil - where the site is currently hosted?

**Comment by evoskuil** [comment]
@dan-mi-sun Sorry, I really don't know. It's been a long time since I looked at it.

**Comment by veox** [comment]
@dan-mi-sun actually, that's a good idea. I'll deploy it after checking what else has changed compared to libbitcoin.org.

**Comment by veox** [comment]
P.S. Scrap last comment, I see it's been taken up [in appropriate repo](https://github.com/libbitcoin/libbitcoin.github.io/issues/2).

**Pull request closed without merging**
