### PR TITLE
New general-purpose URI parsing module

### PR DESCRIPTION
**Pull request by swansontec**
This exists to help with BitID and other things of that nature. The code works, and I've tried to stick to the latest coding standards, but this could probably use good solid review before accepting.

### CODE REVIEW

**Comment by swansontec** [comment]
Also see https://github.com/swansontec/libbitcoin/pull/1 for work that builds on top of this.

**Comment by swansontec** [comment]
Ah, it looks like `encode` should be called `to_string`. Didn't realize that that was a project-wide change.

**Comment by evoskuil** [comment]
Thanks @swansontec, this looks nice.

**Comment by evoskuil** [comment]
@swansontec There's a lot of change right now in wallet. Don't worry about `to_string` - That may end up being limited to the satoshi and blockchain primitives, since `encode` would be ambiguous for them.

I'm using encode/decode for each of the `base58` wallet types, with intermediate array/chunk types and parsed struct/class types. The deserialization exceptions will end up going away for the wallet types as well. I've written `bool` validity operator overrides for each of their class/struct forms. There will be a pull request on this soon.

It's a work in progress, heading towards a more rational view of all primitives, while retaining the core philosophy.

**Pull request merged**
