### PR TITLE
undefined behavior fixed

### PR DESCRIPTION
**Pull request by fpelliccioni**
Error not detected by the unit tests

### CODE REVIEW

**Comment by thecodefactory** [comment]
@fpelliccioni This looks correct.  It doesn't look like a packed struct and is an odd size, so it's likely padded for alignment.  The pointer writes probably succeed most of the time when they shouldn't.  The test would not detect this in that case.

**Comment by fpelliccioni** [comment]
Please see the complete file. It is trying to access to an non existing
array element.

**Comment by thecodefactory** [comment]
Right.  I was saying that your fix looks correct.

**Comment by thecodefactory** [comment]
Not sure why the last travis build is hanging, but merging this.

**Comment by thecodefactory** [comment]
Note: This is probably related to libbitcoin#715

**Comment by evoskuil** [comment]
Nice, thanks!

**Pull request merged**
